### ISSUE TITLE
Add speech recognition

### ISSUE THREAD

**Issue by ArjunAJS143** [susantabiswas/facial-emotion-analyzer#1]
How to add speech recognition with emotion recognition so that it can respond with speech based on our emotion with our phrase.i tried but it not done successfully please help me

**Comment by susantabiswas** [comment]
Sorry due to other commitments adding speech recognition won't be possible.

**Comment by ArjunAJS143** [comment]
is that possible with multiprocessing or multithreading

**Comment by susantabiswas** [comment]
Multithreading / Multiprocessing is very different from what you are trying to do

**Comment by ArjunAJS143** [comment]
ok then no approach is there to do that??

**Comment by susantabiswas** [comment]
No, there are approaches. I am just saying that multithreading is something different than a model for speech recognition. 
One simple pipeline : Have a module which can record sound and then process it.
Have a model trained for speech recognition(difficult part) or you can use a pretrained model if available for this.
Now feed the speech data-->Speech model-->speech output
Now here you can use multithreading:
Have a module which records video feed like the one i have made(you can run this task on a separate thread):
Video feed-->Facial emotion model --> facial output

Now to give the final output you can give weightage  to each of the results, and combine them
to give the final result.

This is a very simple pipeline.

**Comment by ArjunAJS143** [comment]
thanks i will try

**Comment by veacks** [comment]
@ArjunAJS143 You can use Vokaturi (open version) https://developers.vokaturi.com/using/python-sample, it uses the same output neutral, happy, sad, angry and fear

SDK can be found here: https://developers.vokaturi.com/downloads/sdk
