### ISSUE TITLE
How to increase the capture frame rate to 1 frame per second

### ISSUE THREAD

**Issue by xhuiscode** [susantabiswas/facial-emotion-analyzer#5]
How to increase the capture frame rate to 1 frame per second

**Comment by susantabiswas** [comment]
@xhuiscode what do you mean increase to 1 fps? If you are running this on a decent computer, you should already be getting be > 1fps. Otherwise you can experiment with the frame size till you can get high fps.

But if your question is to how to set the fps to 1, then you can try something like below:
```
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FPS, 10)
```

**Comment by xhuiscode** [comment]
> @xhuiscode what do you mean increase to 1 fps? If you are running this on a decent computer, you should already be getting be > 1fps. Otherwise you can experiment with the frame size till you can get high fps.
> 
> But if your question is to how to set the fps to 1, then you can try something like below:
> 
> ```
> cap = cv2.VideoCapture(0)
> cap.set(cv2.CAP_PROP_FPS, 10)
> ```

I'm actually trying to speed up the real time, and this algorithm of yours now counts every frame can you just take one frame per second? If you can, how do you adjust it, otherwise it's a little slow (if you extract every frame and return one frame a second, a minute of video takes 12 minutes to analyze, it is too slow， so i want to lift its speed

**Comment by susantabiswas** [comment]
I would suggest trying these out:
You will find these parameters in the video_main.py method responsible for taking input from webcam. 
1. detection_interval: Controls how often the images are processed for emotion analysis
2. resize_scale: Controls how much the image should be resized.

You can make it run much faster by making the detection_interval(model processing frame rate) higher and controlling the resize_scale paramater.

**Comment by xhuiscode** [comment]
> I would suggest trying these out: You will find these parameters in the video_main.py method responsible for taking input from webcam.
> 
> 1. detection_interval: Controls how often the images are processed for emotion analysis
> 2. resize_scale: Controls how much the image should be resized.
> 
> You can make it run much faster by making the detection_interval(model processing frame rate) higher and controlling the resize_scale paramater.

Thank you very much for your careful answer！Thanks
